#!/bin/bash

nw="/Applications/Orchard.app/Contents/MacOS/node-webkit"

if [ -z "$(pgrep app.js)" ]
  then
      #echo "app.js is running..."
      :
  else
      #echo "starting app.js..."
      node app.js &
fi

${nw} $(pwd) $@
