#!/usr/bin/env ruby

nw = "/Applications/Orchard.app/Contents/MacOS/node-webkit"

res = `ps -ef | grep node | grep app.js | grep -v grep`
print "RES: #{res}"

if res == ''
    puts "starting app.js to serve Orchard with repl support..."
    server = fork do
        `node app.js`
    end
else
    puts "app.js is running..."
end

puts "#{nw} #{Dir.pwd} #{ARGV.join(' ')}"
`#{nw} #{Dir.pwd} #{ARGV.join(' ')}`
